name: Run The Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-lastest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/steup-python@v2
      with:
        python-version: 3.11
    - name: Install dependiences
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Unit Testing
      run: |
        cd ciphers_project
        python3 manage.py test
    - name: Build and push the image
      run: |
          docker login --username mahalawise --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/mahalawise/ciphers-service:latest --file Dockerfile .  
          docker push ghcr.io/mahalawise/ciphers-service:latest 